
on:
   workflow_dispatch:
    
   push:
     branches: [ "main" ]
     paths: 
     - Application/**
 
   pull_request:
     branches: [ "main" ]
     paths: 
     - Application/**

env:
  registryName: wtpw2devopsreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerfilePath: ./Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-restore
    - name: Test
      run: dotnet test ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj --no-build --verbosity normal
  
  docker-build-and-push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.ACR_USERNAME }}
          # Container registry password
          password: ${{ secrets.ACR_PASSWORD }}
          # Container registry server url
          login-server: ${{ env.registryName }}

      - name: Docker build
        run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerfilePath

      - name: Docker Push
        run: docker push $registryName/$repositoryName:$tag
  
  deploy-to-dev:
  
    runs-on: ubuntu-latest
    needs: docker-build-and-push
    environment:
      name: dev
      url: https://dynodemoapp-dev.azurewebsites.net
    
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'wtpw2devops-dev'
          images: ${{env.registryName}}/wth/dotnetcoreapp:${{env.tag}}